<a href="https://colab.research.google.com/github/EricSnunes/AnaliseDeDados/blob/main/PrencherDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_excel('Dados242.xlsx')
df

,Sexo,Idade,Altura,Peso,Renda,Profissão do pai ou mãe,Numero de moradores,número de banheiros na casa,Gênero musical,Distância da Faculdade,Número de Pets na casa,numero do calçado,Hobby
0,FEMININO,21,160,65.0,NaN,VETERINARIO,2,1,POP,7.00,1,38,LER
1,FEMININO,20,177,53.0,NaN,Músico,3,1,MPB,8.00,0,37,Ler
2,Masculino,20,176,66.0,NaN,Corretor,3,4,Indie / Rock,3.40,0,39,Ler e escrever
3,Masculino,20,171,76.0,NaN,Contador,3,1,Rap / Rock,18.00,2,41,Ler e escrever
4,masculino,21,173,72.0,NaN,contador,5,2,Rock,16.00,3,42,treinar
5,Masculino,20,173,124.0,5000.0,Coordenador comercial/ Diarista,3,1,Pagode/Samba,20.00,1,42,Jogar futebol americano
6,Feminino,23,175,69.0,NaN,Gerente de vendas,4,2,Pop/ indie / rock,8.00,0,38,Fotografia e ler
7,Feminino,21,159,51.0,1400.0,Vendedora,3,3,Sertanejo,42.00,2,36,Beber
8,Feminino,22,154,60.0,1900.0,Serralheiro,5,3,POP,8.00,7,35,Teatro
9,Feminino,20,167,52.0,1100.0,Mecânico,3,2,Pop,49.00,3,38,Dançar
10,FEMININO,20,165,65.0,NaN,Policial,4,4,MPB,27.00,2,38,ler
11,FEMININO,19,171,60.0,NaN,NaN,3,1,POP,15.00,1,35,cinema
12,Masculino,23,173,82.0,1550.0,Contador/Finanças,3,2,Rap/R&B,7.00,1,40,Escrever
13,Feminino,20,167,85.0,2623.0,Gerente de projetos,2,1,POP,13.00,2,38,Música
14,FEMININO,22,166,57.0,NaN,EMPRESARIA / ADVOGADO,4,4,TODOS,1.50,0,36,SAIR
15,Feminino,21,155,50.0,1100.0,administrador,4,2,pop/ reggaeton,15.00,0,36,Música
16,Feminino,20,161,65.0,NaN,MECANICO,4,3,KPOP,7.00,1,34,LER
17,Masculino,22,176,65.0,1200.0,Confeiteiro,3,1,Indie / Rock,13.00,0,42,Jogar
18,Masculino,20,193,83.0,2100.0,NaN,5,4,Sertanejo/funk,34.60,0,45,basquete e violão
19,Masculino,22,170,78.0,100.0,Gerente de loja,2,1,RAP,2.70,2,42,Treinar
20,Masculino,20,175,NaN,NaN,Jornalista,4,4,Rock/Metal,0.55,0,42,Jogar
21,Masculino,20,175,71.0,NaN,Engenheiro Elétrico,4,3,Rock/Metal,5.40,0,41,Videogames
22,Masculino,25,172,88.0,NaN,NaN,3,1,rap/reggae,26.00,0,41,NaN
23,Masculino,22,173,82.0,NaN,garçom,5,1,rap,16.00,0,40,JiuJitso
24,Masculino,36,183,84.0,NaN,Advogado,3,1,Rock,5.00,0,42,Jogar futebol
25,NaN,20,173,95.0,4000.0,Analista de dados,4,2,Eletronica / pop,12.00,2,39/40,Desenhar / Música
26,Masculino,21,185,86.0,NaN,Motorista,4,1,Ecletico,15.00,0,44,Jogar
27,Masculino,21,175,60.0,0.0,Assistente social,4,2,Eclético,34.00,0,40/41,Skate
28,Masculino,21,177,55.0,0.0,Tec. Enfermagem / Publicitario,4,3,Rock/ indie-rock/ Eletronica,2.70,1,40,Jogar video game
29,Masculino,21,173,69.0,0.0,Servidor Público,3,4,Eletronica,22.00,3,40,Escrever

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sexo                         29 non-null     object
 1   Idade                        30 non-null     int64
 2   Altura                       30 non-null     int64
 3   Peso                         29 non-null     float64
 4   Renda                        14 non-null     float64
 5   Profissão do pai ou mãe      27 non-null     object
 6   Numero de moradores          30 non-null     int64
 7   número de banheiros na casa  30 non-null     int64
 8   Gênero musical               30 non-null     object
 9   Distância da Faculdade       30 non-null     float64
 10  Número de Pets na casa       30 non-null     int64
 11  numero do calçado            30 non-null     object
 12  Hobby                        29 non-null     object
dtypes: float64(3), int64(5), object(5)
memory usage: 3.2+ KB
None

In [ ]:
df_limpo = df.dropna()
df_limpo

,Sexo,Idade,Altura,Peso,Renda,Profissão do pai ou mãe,Numero de moradores,número de banheiros na casa,Gênero musical,Distância da Faculdade,Número de Pets na casa,numero do calçado,Hobby
5,Masculino,20,173,124.0,5000.0,Coordenador comercial/ Diarista,3,1,Pagode/Samba,20.0,1,42,Jogar futebol americano
7,Feminino,21,159,51.0,1400.0,Vendedora,3,3,Sertanejo,42.0,2,36,Beber
8,Feminino,22,154,60.0,1900.0,Serralheiro,5,3,POP,8.0,7,35,Teatro
9,Feminino,20,167,52.0,1100.0,Mecânico,3,2,Pop,49.0,3,38,Dançar
12,Masculino,23,173,82.0,1550.0,Contador/Finanças,3,2,Rap/R&B,7.0,1,40,Escrever
13,Feminino,20,167,85.0,2623.0,Gerente de projetos,2,1,POP,13.0,2,38,Música
15,Feminino,21,155,50.0,1100.0,administrador,4,2,pop/ reggaeton,15.0,0,36,Música
17,Masculino,22,176,65.0,1200.0,Confeiteiro,3,1,Indie / Rock,13.0,0,42,Jogar
19,Masculino,22,170,78.0,100.0,Gerente de loja,2,1,RAP,2.7,2,42,Treinar
27,Masculino,21,175,60.0,0.0,Assistente social,4,2,Eclético,34.0,0,40/41,Skate
28,Masculino,21,177,55.0,0.0,Tec. Enfermagem / Publicitario,4,3,Rock/ indie-rock/ Eletronica,2.7,1,40,Jogar video game
29,Masculino,21,173,69.0,0.0,Servidor Público,3,4,Eletronica,22.0,3,40,Escrever

In [ ]:
#preencher dados faltantes com a media da coluna
media_renda = df['Renda'].mean()
df['Renda'] = df['Renda'].fillna(media_renda)
df

,Sexo,Idade,Altura,Peso,Renda,Profissão do pai ou mãe,Numero de moradores,número de banheiros na casa,Gênero musical,Distância da Faculdade,Número de Pets na casa,numero do calçado,Hobby
0,FEMININO,21,160,65.0,1576.642857,VETERINARIO,2,1,POP,7.00,1,38,LER
1,FEMININO,20,177,53.0,1576.642857,Músico,3,1,MPB,8.00,0,37,Ler
2,Masculino,20,176,66.0,1576.642857,Corretor,3,4,Indie / Rock,3.40,0,39,Ler e escrever
3,Masculino,20,171,76.0,1576.642857,Contador,3,1,Rap / Rock,18.00,2,41,Ler e escrever
4,masculino,21,173,72.0,1576.642857,contador,5,2,Rock,16.00,3,42,treinar
5,Masculino,20,173,124.0,5000.000000,Coordenador comercial/ Diarista,3,1,Pagode/Samba,20.00,1,42,Jogar futebol americano
6,Feminino,23,175,69.0,1576.642857,Gerente de vendas,4,2,Pop/ indie / rock,8.00,0,38,Fotografia e ler
7,Feminino,21,159,51.0,1400.000000,Vendedora,3,3,Sertanejo,42.00,2,36,Beber
8,Feminino,22,154,60.0,1900.000000,Serralheiro,5,3,POP,8.00,7,35,Teatro
9,Feminino,20,167,52.0,1100.000000,Mecânico,3,2,Pop,49.00,3,38,Dançar
10,FEMININO,20,165,65.0,1576.642857,Policial,4,4,MPB,27.00,2,38,ler
11,FEMININO,19,171,60.0,1576.642857,NaN,3,1,POP,15.00,1,35,cinema
12,Masculino,23,173,82.0,1550.000000,Contador/Finanças,3,2,Rap/R&B,7.00,1,40,Escrever
13,Feminino,20,167,85.0,2623.000000,Gerente de projetos,2,1,POP,13.00,2,38,Música
14,FEMININO,22,166,57.0,1576.642857,EMPRESARIA / ADVOGADO,4,4,TODOS,1.50,0,36,SAIR
15,Feminino,21,155,50.0,1100.000000,administrador,4,2,pop/ reggaeton,15.00,0,36,Música
16,Feminino,20,161,65.0,1576.642857,MECANICO,4,3,KPOP,7.00,1,34,LER
17,Masculino,22,176,65.0,1200.000000,Confeiteiro,3,1,Indie / Rock,13.00,0,42,Jogar
18,Masculino,20,193,83.0,2100.000000,NaN,5,4,Sertanejo/funk,34.60,0,45,basquete e violão
19,Masculino,22,170,78.0,100.000000,Gerente de loja,2,1,RAP,2.70,2,42,Treinar
20,Masculino,20,175,NaN,1576.642857,Jornalista,4,4,Rock/Metal,0.55,0,42,Jogar
21,Masculino,20,175,71.0,1576.642857,Engenheiro Elétrico,4,3,Rock/Metal,5.40,0,41,Videogames
22,Masculino,25,172,88.0,1576.642857,NaN,3,1,rap/reggae,26.00,0,41,NaN
23,Masculino,22,173,82.0,1576.642857,garçom,5,1,rap,16.00,0,40,JiuJitso
24,Masculino,36,183,84.0,1576.642857,Advogado,3,1,Rock,5.00,0,42,Jogar futebol
25,NaN,20,173,95.0,4000.000000,Analista de dados,4,2,Eletronica / pop,12.00,2,39/40,Desenhar / Música
26,Masculino,21,185,86.0,1576.642857,Motorista,4,1,Ecletico,15.00,0,44,Jogar
27,Masculino,21,175,60.0,0.000000,Assistente social,4,2,Eclético,34.00,0,40/41,Skate
28,Masculino,21,177,55.0,0.000000,Tec. Enfermagem / Publicitario,4,3,Rock/ indie-rock/ Eletronica,2.70,1,40,Jogar video game
29,Masculino,21,173,69.0,0.000000,Servidor Público,3,4,Eletronica,22.00,3,40,Escrever

In [ ]:
#preencher dados faltantes com a media da coluna
media_peso = df['Peso'].mean()
df['Peso'] = df['Peso'].fillna(media_peso)
df

,Sexo,Idade,Altura,Peso,Renda,Profissão do pai ou mãe,Numero de moradores,número de banheiros na casa,Gênero musical,Distância da Faculdade,Número de Pets na casa,numero do calçado,Hobby
0,FEMININO,21,160,65.000000,1576.642857,VETERINARIO,2,1,POP,7.00,1,38,LER
1,FEMININO,20,177,53.000000,1576.642857,Músico,3,1,MPB,8.00,0,37,Ler
2,Masculino,20,176,66.000000,1576.642857,Corretor,3,4,Indie / Rock,3.40,0,39,Ler e escrever
3,Masculino,20,171,76.000000,1576.642857,Contador,3,1,Rap / Rock,18.00,2,41,Ler e escrever
4,masculino,21,173,72.000000,1576.642857,contador,5,2,Rock,16.00,3,42,treinar
5,Masculino,20,173,124.000000,5000.000000,Coordenador comercial/ Diarista,3,1,Pagode/Samba,20.00,1,42,Jogar futebol americano
6,Feminino,23,175,69.000000,1576.642857,Gerente de vendas,4,2,Pop/ indie / rock,8.00,0,38,Fotografia e ler
7,Feminino,21,159,51.000000,1400.000000,Vendedora,3,3,Sertanejo,42.00,2,36,Beber
8,Feminino,22,154,60.000000,1900.000000,Serralheiro,5,3,POP,8.00,7,35,Teatro
9,Feminino,20,167,52.000000,1100.000000,Mecânico,3,2,Pop,49.00,3,38,Dançar
10,FEMININO,20,165,65.000000,1576.642857,Policial,4,4,MPB,27.00,2,38,ler
11,FEMININO,19,171,60.000000,1576.642857,NaN,3,1,POP,15.00,1,35,cinema
12,Masculino,23,173,82.000000,1550.000000,Contador/Finanças,3,2,Rap/R&B,7.00,1,40,Escrever
13,Feminino,20,167,85.000000,2623.000000,Gerente de projetos,2,1,POP,13.00,2,38,Música
14,FEMININO,22,166,57.000000,1576.642857,EMPRESARIA / ADVOGADO,4,4,TODOS,1.50,0,36,SAIR
15,Feminino,21,155,50.000000,1100.000000,administrador,4,2,pop/ reggaeton,15.00,0,36,Música
16,Feminino,20,161,65.000000,1576.642857,MECANICO,4,3,KPOP,7.00,1,34,LER
17,Masculino,22,176,65.000000,1200.000000,Confeiteiro,3,1,Indie / Rock,13.00,0,42,Jogar
18,Masculino,20,193,83.000000,2100.000000,NaN,5,4,Sertanejo/funk,34.60,0,45,basquete e violão
19,Masculino,22,170,78.000000,100.000000,Gerente de loja,2,1,RAP,2.70,2,42,Treinar
20,Masculino,20,175,71.310345,1576.642857,Jornalista,4,4,Rock/Metal,0.55,0,42,Jogar
21,Masculino,20,175,71.000000,1576.642857,Engenheiro Elétrico,4,3,Rock/Metal,5.40,0,41,Videogames
22,Masculino,25,172,88.000000,1576.642857,NaN,3,1,rap/reggae,26.00,0,41,NaN
23,Masculino,22,173,82.000000,1576.642857,garçom,5,1,rap,16.00,0,40,JiuJitso
24,Masculino,36,183,84.000000,1576.642857,Advogado,3,1,Rock,5.00,0,42,Jogar futebol
25,NaN,20,173,95.000000,4000.000000,Analista de dados,4,2,Eletronica / pop,12.00,2,39/40,Desenhar / Música
26,Masculino,21,185,86.000000,1576.642857,Motorista,4,1,Ecletico,15.00,0,44,Jogar
27,Masculino,21,175,60.000000,0.000000,Assistente social,4,2,Eclético,34.00,0,40/41,Skate
28,Masculino,21,177,55.000000,0.000000,Tec. Enfermagem / Publicitario,4,3,Rock/ indie-rock/ Eletronica,2.70,1,40,Jogar video game
29,Masculino,21,173,69.000000,0.000000,Servidor Público,3,4,Eletronica,22.00,3,40,Escrever

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sexo                         29 non-null     object
 1   Idade                        30 non-null     int64
 2   Altura                       30 non-null     int64
 3   Peso                         30 non-null     float64
 4   Renda                        30 non-null     float64
 5   Profissão do pai ou mãe      27 non-null     object
 6   Numero de moradores          30 non-null     int64
 7   número de banheiros na casa  30 non-null     int64
 8   Gênero musical               30 non-null     object
 9   Distância da Faculdade       30 non-null     float64
 10  Número de Pets na casa       30 non-null     int64
 11  numero do calçado            30 non-null     object
 12  Hobby                        29 non-null     object
dtypes: float64(3), int64(5), object(5)
memory usage: 3.2+ KB
None

In [ ]:
#selecione apenas as colunas numericas
datanum.to_csv('dados242limpos.csv', index=False)